# Generated by Django 3.0.6 on 2020-05-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=7)),
                ('create_dt', models.DateField(auto_now=True)),
            ],
        ),
    ]
