# Generated by Django 3.0.6 on 2020-05-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stud_ID', models.CharField(max_length=10)),
                ('Stud_Name', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=15)),
                ('Marks', models.IntegerField()),
            ],
        ),
    ]
