# Generated by Django 3.0.6 on 2020-05-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Stud',
        ),
    ]
