# Generated by Django 3.0.6 on 2020-05-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('edesign', models.CharField(max_length=30)),
                ('leave_bal', models.IntegerField()),
                ('dt', models.DateField(auto_now=True)),
            ],
        ),
    ]
